version: "3.9"

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"

  project-service:
    build: ./project-service
    ports:
      - "3002:3002"

  task-service:
    build: ./task-service
    ports:
      - "3003:3003"

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"